fix: download to temp file to prevent loss of notes
IceWhaleTech/CasaOS-Installer pull request #165
Opened 2024-07-04 03:42 UTC by orca-zhang

2024-07-05 04:55 UTC, CorrectRoadH requested changes

2024-07-05 04:55 UTC, CorrectRoadH commented on service/release.go
> +	return releaseFilePath, os.Rename(releaseFilePathTemp, releaseFilePath)
这里还少一个逻辑，在rauc online初始化的时候从上次保存的本地release读出来。来作为从网络拿到之前的fallback。

2024-07-08 10:38 UTC, CorrectRoadH commented on test/service/rauc_offline_test.go
> +func initEnv(t *testing.T) (string, context.Context, *service.RAUCOfflineService) {
这里是一个测试用例还是一个fixtures?

2024-07-09 03:07 UTC, orca-zhang commented on test/service/rauc_offline_test.go
> +func initEnv(t *testing.T) (string, context.Context, *service.RAUCOfflineService) {
提取公共函数，Sonar静态检查报错，单文件重复代码率超过3%

2024-07-09 03:25 UTC, orca-zhang commented on test/service/rauc_offline_test.go
> +func initEnv(t *testing.T) (string, context.Context, *service.RAUCOfflineService) {
重新作了调整，改名为setUp，然后抽出公用变量为全局变量

2024-07-09 03:52 UTC, CorrectRoadH approved these changes
LGTM

2024-07-09 04:04 UTC, merged